/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SeasonalExperiencesRouteImport } from './routes/seasonal-experiences'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivateToursRouteImport } from './routes/private-tours'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlanMyTripRouteImport } from './routes/plan-my-trip'
import { Route as LuxuryToursRouteImport } from './routes/luxury-tours'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupToursRouteImport } from './routes/group-tours'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TravelGuidesIndexRouteImport } from './routes/travel-guides.index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TravelGuidesSlugRouteImport } from './routes/travel-guides.$slug'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedDashboardTripRequestsRouteImport } from './routes/_authenticated/dashboard.trip-requests'
import { Route as AuthenticatedDashboardSavedToursRouteImport } from './routes/_authenticated/dashboard.saved-tours'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated/dashboard.notifications'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard.messages'
import { Route as AuthenticatedDashboardFavouritesRouteImport } from './routes/_authenticated/dashboard.favourites'
import { Route as AuthenticatedDashboardChangePasswordRouteImport } from './routes/_authenticated/dashboard.change-password'
import { Route as AuthenticatedDashboardBookingsRouteImport } from './routes/_authenticated/dashboard.bookings'
import { Route as AuthenticatedAdminVehiclesRouteImport } from './routes/_authenticated/admin.vehicles'
import { Route as AuthenticatedAdminTripRequestsRouteImport } from './routes/_authenticated/admin.trip-requests'
import { Route as AuthenticatedAdminToursRouteImport } from './routes/_authenticated/admin.tours'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin.testimonials'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin.faqs'
import { Route as AuthenticatedAdminDestinationsRouteImport } from './routes/_authenticated/admin.destinations'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminCarRentalRequestsRouteImport } from './routes/_authenticated/admin.car-rental-requests'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonalExperiencesRoute = SeasonalExperiencesRouteImport.update({
  id: '/seasonal-experiences',
  path: '/seasonal-experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateToursRoute = PrivateToursRouteImport.update({
  id: '/private-tours',
  path: '/private-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanMyTripRoute = PlanMyTripRouteImport.update({
  id: '/plan-my-trip',
  path: '/plan-my-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxuryToursRoute = LuxuryToursRouteImport.update({
  id: '/luxury-tours',
  path: '/luxury-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupToursRoute = GroupToursRouteImport.update({
  id: '/group-tours',
  path: '/group-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelGuidesIndexRoute = TravelGuidesIndexRouteImport.update({
  id: '/travel-guides/',
  path: '/travel-guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelGuidesSlugRoute = TravelGuidesSlugRouteImport.update({
  id: '/travel-guides/$slug',
  path: '/travel-guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDashboardTripRequestsRoute =
  AuthenticatedDashboardTripRequestsRouteImport.update({
    id: '/trip-requests',
    path: '/trip-requests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSavedToursRoute =
  AuthenticatedDashboardSavedToursRouteImport.update({
    id: '/saved-tours',
    path: '/saved-tours',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFavouritesRoute =
  AuthenticatedDashboardFavouritesRouteImport.update({
    id: '/favourites',
    path: '/favourites',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardChangePasswordRoute =
  AuthenticatedDashboardChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBookingsRoute =
  AuthenticatedDashboardBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminVehiclesRoute =
  AuthenticatedAdminVehiclesRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTripRequestsRoute =
  AuthenticatedAdminTripRequestsRouteImport.update({
    id: '/trip-requests',
    path: '/trip-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminToursRoute = AuthenticatedAdminToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDestinationsRoute =
  AuthenticatedAdminDestinationsRouteImport.update({
    id: '/destinations',
    path: '/destinations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCarRentalRequestsRoute =
  AuthenticatedAdminCarRentalRequestsRouteImport.update({
    id: '/car-rental-requests',
    path: '/car-rental-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/group-tours': typeof GroupToursRoute
  '/login': typeof LoginRoute
  '/luxury-tours': typeof LuxuryToursRoute
  '/plan-my-trip': typeof PlanMyTripRoute
  '/privacy': typeof PrivacyRoute
  '/private-tours': typeof PrivateToursRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/seasonal-experiences': typeof SeasonalExperiencesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/travel-guides/$slug': typeof TravelGuidesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/travel-guides/': typeof TravelGuidesIndexRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/car-rental-requests': typeof AuthenticatedAdminCarRentalRequestsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/destinations': typeof AuthenticatedAdminDestinationsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/tours': typeof AuthenticatedAdminToursRoute
  '/admin/trip-requests': typeof AuthenticatedAdminTripRequestsRoute
  '/admin/vehicles': typeof AuthenticatedAdminVehiclesRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/change-password': typeof AuthenticatedDashboardChangePasswordRoute
  '/dashboard/favourites': typeof AuthenticatedDashboardFavouritesRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/saved-tours': typeof AuthenticatedDashboardSavedToursRoute
  '/dashboard/trip-requests': typeof AuthenticatedDashboardTripRequestsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/group-tours': typeof GroupToursRoute
  '/login': typeof LoginRoute
  '/luxury-tours': typeof LuxuryToursRoute
  '/plan-my-trip': typeof PlanMyTripRoute
  '/privacy': typeof PrivacyRoute
  '/private-tours': typeof PrivateToursRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/seasonal-experiences': typeof SeasonalExperiencesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/travel-guides/$slug': typeof TravelGuidesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/tours': typeof ToursIndexRoute
  '/travel-guides': typeof TravelGuidesIndexRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/car-rental-requests': typeof AuthenticatedAdminCarRentalRequestsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/destinations': typeof AuthenticatedAdminDestinationsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/tours': typeof AuthenticatedAdminToursRoute
  '/admin/trip-requests': typeof AuthenticatedAdminTripRequestsRoute
  '/admin/vehicles': typeof AuthenticatedAdminVehiclesRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/change-password': typeof AuthenticatedDashboardChangePasswordRoute
  '/dashboard/favourites': typeof AuthenticatedDashboardFavouritesRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/saved-tours': typeof AuthenticatedDashboardSavedToursRoute
  '/dashboard/trip-requests': typeof AuthenticatedDashboardTripRequestsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/group-tours': typeof GroupToursRoute
  '/login': typeof LoginRoute
  '/luxury-tours': typeof LuxuryToursRoute
  '/plan-my-trip': typeof PlanMyTripRoute
  '/privacy': typeof PrivacyRoute
  '/private-tours': typeof PrivateToursRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/seasonal-experiences': typeof SeasonalExperiencesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/travel-guides/$slug': typeof TravelGuidesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/travel-guides/': typeof TravelGuidesIndexRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/car-rental-requests': typeof AuthenticatedAdminCarRentalRequestsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/destinations': typeof AuthenticatedAdminDestinationsRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/tours': typeof AuthenticatedAdminToursRoute
  '/_authenticated/admin/trip-requests': typeof AuthenticatedAdminTripRequestsRoute
  '/_authenticated/admin/vehicles': typeof AuthenticatedAdminVehiclesRoute
  '/_authenticated/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/_authenticated/dashboard/change-password': typeof AuthenticatedDashboardChangePasswordRoute
  '/_authenticated/dashboard/favourites': typeof AuthenticatedDashboardFavouritesRoute
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/saved-tours': typeof AuthenticatedDashboardSavedToursRoute
  '/_authenticated/dashboard/trip-requests': typeof AuthenticatedDashboardTripRequestsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/group-tours'
    | '/login'
    | '/luxury-tours'
    | '/plan-my-trip'
    | '/privacy'
    | '/private-tours'
    | '/reset-password'
    | '/reviews'
    | '/seasonal-experiences'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/admin/login'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/services/$slug'
    | '/tours/$slug'
    | '/travel-guides/$slug'
    | '/blog/'
    | '/destinations/'
    | '/services/'
    | '/tours/'
    | '/travel-guides/'
    | '/admin/blog'
    | '/admin/car-rental-requests'
    | '/admin/customers'
    | '/admin/destinations'
    | '/admin/faqs'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/tours'
    | '/admin/trip-requests'
    | '/admin/vehicles'
    | '/dashboard/bookings'
    | '/dashboard/change-password'
    | '/dashboard/favourites'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/saved-tours'
    | '/dashboard/trip-requests'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/group-tours'
    | '/login'
    | '/luxury-tours'
    | '/plan-my-trip'
    | '/privacy'
    | '/private-tours'
    | '/reset-password'
    | '/reviews'
    | '/seasonal-experiences'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/login'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/services/$slug'
    | '/tours/$slug'
    | '/travel-guides/$slug'
    | '/blog'
    | '/destinations'
    | '/services'
    | '/tours'
    | '/travel-guides'
    | '/admin/blog'
    | '/admin/car-rental-requests'
    | '/admin/customers'
    | '/admin/destinations'
    | '/admin/faqs'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/tours'
    | '/admin/trip-requests'
    | '/admin/vehicles'
    | '/dashboard/bookings'
    | '/dashboard/change-password'
    | '/dashboard/favourites'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/saved-tours'
    | '/dashboard/trip-requests'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/group-tours'
    | '/login'
    | '/luxury-tours'
    | '/plan-my-trip'
    | '/privacy'
    | '/private-tours'
    | '/reset-password'
    | '/reviews'
    | '/seasonal-experiences'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/admin/login'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/services/$slug'
    | '/tours/$slug'
    | '/travel-guides/$slug'
    | '/blog/'
    | '/destinations/'
    | '/services/'
    | '/tours/'
    | '/travel-guides/'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/car-rental-requests'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/destinations'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/tours'
    | '/_authenticated/admin/trip-requests'
    | '/_authenticated/admin/vehicles'
    | '/_authenticated/dashboard/bookings'
    | '/_authenticated/dashboard/change-password'
    | '/_authenticated/dashboard/favourites'
    | '/_authenticated/dashboard/messages'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/saved-tours'
    | '/_authenticated/dashboard/trip-requests'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GroupToursRoute: typeof GroupToursRoute
  LoginRoute: typeof LoginRoute
  LuxuryToursRoute: typeof LuxuryToursRoute
  PlanMyTripRoute: typeof PlanMyTripRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivateToursRoute: typeof PrivateToursRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  SeasonalExperiencesRoute: typeof SeasonalExperiencesRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ToursSlugRoute: typeof ToursSlugRoute
  TravelGuidesSlugRoute: typeof TravelGuidesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ToursIndexRoute: typeof ToursIndexRoute
  TravelGuidesIndexRoute: typeof TravelGuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasonal-experiences': {
      id: '/seasonal-experiences'
      path: '/seasonal-experiences'
      fullPath: '/seasonal-experiences'
      preLoaderRoute: typeof SeasonalExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-tours': {
      id: '/private-tours'
      path: '/private-tours'
      fullPath: '/private-tours'
      preLoaderRoute: typeof PrivateToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-my-trip': {
      id: '/plan-my-trip'
      path: '/plan-my-trip'
      fullPath: '/plan-my-trip'
      preLoaderRoute: typeof PlanMyTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-tours': {
      id: '/luxury-tours'
      path: '/luxury-tours'
      fullPath: '/luxury-tours'
      preLoaderRoute: typeof LuxuryToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-tours': {
      id: '/group-tours'
      path: '/group-tours'
      fullPath: '/group-tours'
      preLoaderRoute: typeof GroupToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-guides/': {
      id: '/travel-guides/'
      path: '/travel-guides'
      fullPath: '/travel-guides/'
      preLoaderRoute: typeof TravelGuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-guides/$slug': {
      id: '/travel-guides/$slug'
      path: '/travel-guides/$slug'
      fullPath: '/travel-guides/$slug'
      preLoaderRoute: typeof TravelGuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/trip-requests': {
      id: '/_authenticated/dashboard/trip-requests'
      path: '/trip-requests'
      fullPath: '/dashboard/trip-requests'
      preLoaderRoute: typeof AuthenticatedDashboardTripRequestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/saved-tours': {
      id: '/_authenticated/dashboard/saved-tours'
      path: '/saved-tours'
      fullPath: '/dashboard/saved-tours'
      preLoaderRoute: typeof AuthenticatedDashboardSavedToursRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/favourites': {
      id: '/_authenticated/dashboard/favourites'
      path: '/favourites'
      fullPath: '/dashboard/favourites'
      preLoaderRoute: typeof AuthenticatedDashboardFavouritesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/change-password': {
      id: '/_authenticated/dashboard/change-password'
      path: '/change-password'
      fullPath: '/dashboard/change-password'
      preLoaderRoute: typeof AuthenticatedDashboardChangePasswordRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bookings': {
      id: '/_authenticated/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardBookingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/vehicles': {
      id: '/_authenticated/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AuthenticatedAdminVehiclesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/trip-requests': {
      id: '/_authenticated/admin/trip-requests'
      path: '/trip-requests'
      fullPath: '/admin/trip-requests'
      preLoaderRoute: typeof AuthenticatedAdminTripRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tours': {
      id: '/_authenticated/admin/tours'
      path: '/tours'
      fullPath: '/admin/tours'
      preLoaderRoute: typeof AuthenticatedAdminToursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/destinations': {
      id: '/_authenticated/admin/destinations'
      path: '/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AuthenticatedAdminDestinationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/car-rental-requests': {
      id: '/_authenticated/admin/car-rental-requests'
      path: '/car-rental-requests'
      fullPath: '/admin/car-rental-requests'
      preLoaderRoute: typeof AuthenticatedAdminCarRentalRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminCarRentalRequestsRoute: typeof AuthenticatedAdminCarRentalRequestsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDestinationsRoute: typeof AuthenticatedAdminDestinationsRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminToursRoute: typeof AuthenticatedAdminToursRoute
  AuthenticatedAdminTripRequestsRoute: typeof AuthenticatedAdminTripRequestsRoute
  AuthenticatedAdminVehiclesRoute: typeof AuthenticatedAdminVehiclesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminCarRentalRequestsRoute:
    AuthenticatedAdminCarRentalRequestsRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminDestinationsRoute: AuthenticatedAdminDestinationsRoute,
  AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminToursRoute: AuthenticatedAdminToursRoute,
  AuthenticatedAdminTripRequestsRoute: AuthenticatedAdminTripRequestsRoute,
  AuthenticatedAdminVehiclesRoute: AuthenticatedAdminVehiclesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBookingsRoute: typeof AuthenticatedDashboardBookingsRoute
  AuthenticatedDashboardChangePasswordRoute: typeof AuthenticatedDashboardChangePasswordRoute
  AuthenticatedDashboardFavouritesRoute: typeof AuthenticatedDashboardFavouritesRoute
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRoute
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardSavedToursRoute: typeof AuthenticatedDashboardSavedToursRoute
  AuthenticatedDashboardTripRequestsRoute: typeof AuthenticatedDashboardTripRequestsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBookingsRoute: AuthenticatedDashboardBookingsRoute,
    AuthenticatedDashboardChangePasswordRoute:
      AuthenticatedDashboardChangePasswordRoute,
    AuthenticatedDashboardFavouritesRoute:
      AuthenticatedDashboardFavouritesRoute,
    AuthenticatedDashboardMessagesRoute: AuthenticatedDashboardMessagesRoute,
    AuthenticatedDashboardNotificationsRoute:
      AuthenticatedDashboardNotificationsRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardSavedToursRoute:
      AuthenticatedDashboardSavedToursRoute,
    AuthenticatedDashboardTripRequestsRoute:
      AuthenticatedDashboardTripRequestsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GroupToursRoute: GroupToursRoute,
  LoginRoute: LoginRoute,
  LuxuryToursRoute: LuxuryToursRoute,
  PlanMyTripRoute: PlanMyTripRoute,
  PrivacyRoute: PrivacyRoute,
  PrivateToursRoute: PrivateToursRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  SeasonalExperiencesRoute: SeasonalExperiencesRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ToursSlugRoute: ToursSlugRoute,
  TravelGuidesSlugRoute: TravelGuidesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ToursIndexRoute: ToursIndexRoute,
  TravelGuidesIndexRoute: TravelGuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
